export const fakeBlogsData = [
  {
    image: "/vercel.svg",
    date: " 7 march, 2021",
    writer: "John Doe",
    title: "fdk dfksa kfdks",
    blogText: `Lorem ipsum dolor sit amet consectetur, adipisicing elit.Dignissimos, molestiae?`,
    tags: ["child", "education", "money"],
    catergory: "design",
    facebookLink: "www.facebook.com",
    instagramLink: "www.instagram.com",
    twitterLink: "www.twitter.com",
  },
  {
    image: "/vercel.svg",
    date: " 7 march, 2021",
    writer: "John Doe",
    title: "fdk dfksa kfdks",
    blogText: `Lorem ipsum dolor sit amet consectetur, adipisicing elit.Dignissimos, molestiae?`,
    tags: ["child", "education", "money"],
    catergory: "design",
    facebookLink: "www.facebook.com",
    instagramLink: "www.instagram.com",
    twitterLink: "www.twitter.com",
  },
  {
    image: "/vercel.svg",
    date: " 7 march, 2021",
    writer: "John Doe",
    title: "fdk dfksa kfdks",
    blogText: `Lorem ipsum dolor sit amet consectetur, adipisicing elit.Dignissimos, molestiae?`,
    tags: ["child", "education", "money"],
    catergory: "design",
    facebookLink: "www.facebook.com",
    instagramLink: "www.instagram.com",
    twitterLink: "www.twitter.com",
  },
  {
    image: "/vercel.svg",
    date: " 7 march, 2021",
    writer: "John Doe",
    title: "fdk dfksa kfdks",
    blogText: `Lorem ipsum dolor sit amet consectetur, adipisicing elit.Dignissimos, molestiae?`,
    tags: ["child", "education", "money"],
    catergory: "design",
    facebookLink: "www.facebook.com",
    instagramLink: "www.instagram.com",
    twitterLink: "www.twitter.com",
  },
];
