import Head from 'next/head'
import '../scss/main.scss';
import HeaderNav from '../components/common/HeaderNav';
import { useRouter } from 'next/dist/client/router';
import Footer from '../components/common/footer/Footer';

function MyApp({ Component, pageProps }) {
  const router = useRouter();
  return <>
    <Head>
      <title>People choice agency</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.png" />
    </Head>
    {
      router.pathname !== '/' &&
      <HeaderNav />
    }
    <Component {...pageProps} />
    <Footer/>
  </>
}

export default MyApp
