import React from 'react';
import Head from "next/head";
import AboutUs from "../components/AboutUs/AboutUs";


const about = () => {
    return (
      <div>
        <Head>
          <title>About Us</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.png" />
        </Head>
        <AboutUs />
      </div>
    );
};

export default about;