import ContactUs from '../components/ContactUS/ContactUs'
import Head from 'next/head'


function contact() {
    return (
    <div>
      <Head>
        <title>Contact Us</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <ContactUs/>
    </div>
  )
}

export default contact;