import Head from 'next/head'

export default function Home() {

  return (
    <div>
      <Head>
        <title>People choice agency client</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="display-1 bg-primary">Welcome to people choice agency</h1>
    </div>
  )
}
