import React from 'react';
import Head from "next/head";
import ServiceDetails from '../components/ServiceDetails/ServiceDetails';

const service = () => {
    return (
      <div>
        <Head>
          <title>Service Details</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.png" />
        </Head>
        <ServiceDetails/>
      </div>
    );
};

export default service;